//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:46:26 PM CST 
//


package utsw.bicf.answer.model.ehr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isSubclonal" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isEquivocal" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="dnaFraction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "AlterationProperty")
public class AlterationProperty {

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "isSubclonal")
    protected Boolean isSubclonal;
    @XmlAttribute(name = "isEquivocal")
    protected Boolean isEquivocal;
    @XmlAttribute(name = "dnaFraction")
    protected String dnaFraction;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isSubclonal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSubclonal() {
        return isSubclonal;
    }

    /**
     * Sets the value of the isSubclonal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSubclonal(Boolean value) {
        this.isSubclonal = value;
    }

    /**
     * Gets the value of the isEquivocal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEquivocal() {
        return isEquivocal;
    }

    /**
     * Sets the value of the isEquivocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEquivocal(Boolean value) {
        this.isEquivocal = value;
    }

    /**
     * Gets the value of the dnaFraction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnaFraction() {
        return dnaFraction;
    }

    /**
     * Sets the value of the dnaFraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnaFraction(String value) {
        this.dnaFraction = value;
    }

}
