//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:46:26 PM CST 
//


package utsw.bicf.answer.model.ehr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Name" minOccurs="0"/>
 *         &lt;element ref="{}AlterationProperties" minOccurs="0"/>
 *         &lt;element ref="{}Relavance" minOccurs="0"/>
 *         &lt;element ref="{}Interpretation" minOccurs="0"/>
 *         &lt;element ref="{}Indication" minOccurs="0"/>
 *         &lt;element ref="{}Include" minOccurs="0"/>
 *         &lt;element ref="{}ClinicalTrialNote" minOccurs="0"/>
 *         &lt;element ref="{}Therapies" minOccurs="0"/>
 *         &lt;element ref="{}ReferenceLinks" minOccurs="0"/>
 *         &lt;element ref="{}ClinicalTrialLinks" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Alteration")
public class Alteration {

    @XmlElementRefs({
        @XmlElementRef(name = "Name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Relavance", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ClinicalTrialLinks", type = ClinicalTrialLinks.class, required = false),
        @XmlElementRef(name = "Interpretation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ClinicalTrialNote", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Include", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ReferenceLinks", type = ReferenceLinks.class, required = false),
        @XmlElementRef(name = "Indication", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AlterationProperties", type = AlterationProperties.class, required = false),
        @XmlElementRef(name = "Therapies", type = Therapies.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link ClinicalTrialLinks }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link ReferenceLinks }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link AlterationProperties }
     * {@link Therapies }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
