//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:28:17 PM CST 
//


package utsw.bicf.answer.model.ehr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CopyNumberAlteration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CopyNumberAlteration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://foundationmedicine.com/compbio/variant-report-external}Variant">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="dna-evidence" type="{http://foundationmedicine.com/compbio/variant-report-external}CopyNumberAlterationDnaEvidence"/>
 *         &lt;element name="rna-evidence" type="{http://foundationmedicine.com/compbio/variant-report-external}CopyNumberAlterationRnaEvidence"/>
 *       &lt;/choice>
 *       &lt;attribute name="copy-number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="gene" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="number-of-exons" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="position" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ratio" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="type" use="required" type="{http://foundationmedicine.com/compbio/variant-report-external}CopyNumberAlterationType" />
 *       &lt;attribute name="segment-length" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CopyNumberAlteration", propOrder = {
    "dnaEvidenceOrRnaEvidence"
})
public class CopyNumberAlteration
    extends Variant
{

    @XmlElements({
        @XmlElement(name = "dna-evidence", type = CopyNumberAlterationDnaEvidence.class),
        @XmlElement(name = "rna-evidence", type = CopyNumberAlterationRnaEvidence.class)
    })
    protected List<VariantEvidence> dnaEvidenceOrRnaEvidence;
    @XmlAttribute(name = "copy-number")
    protected Integer copyNumber;
    @XmlAttribute(name = "gene", required = true)
    protected String gene;
    @XmlAttribute(name = "number-of-exons", required = true)
    protected String numberOfExons;
    @XmlAttribute(name = "position", required = true)
    protected String position;
    @XmlAttribute(name = "ratio", required = true)
    protected float ratio;
    @XmlAttribute(name = "type", required = true)
    protected CopyNumberAlterationType type;
    @XmlAttribute(name = "segment-length")
    protected Integer segmentLength;

    /**
     * Gets the value of the dnaEvidenceOrRnaEvidence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dnaEvidenceOrRnaEvidence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDnaEvidenceOrRnaEvidence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CopyNumberAlterationDnaEvidence }
     * {@link CopyNumberAlterationRnaEvidence }
     * 
     * 
     */
    public List<VariantEvidence> getDnaEvidenceOrRnaEvidence() {
        if (dnaEvidenceOrRnaEvidence == null) {
            dnaEvidenceOrRnaEvidence = new ArrayList<VariantEvidence>();
        }
        return this.dnaEvidenceOrRnaEvidence;
    }

    /**
     * Gets the value of the copyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCopyNumber() {
        return copyNumber;
    }

    /**
     * Sets the value of the copyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCopyNumber(Integer value) {
        this.copyNumber = value;
    }

    /**
     * Gets the value of the gene property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGene() {
        return gene;
    }

    /**
     * Sets the value of the gene property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGene(String value) {
        this.gene = value;
    }

    /**
     * Gets the value of the numberOfExons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfExons() {
        return numberOfExons;
    }

    /**
     * Sets the value of the numberOfExons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfExons(String value) {
        this.numberOfExons = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the ratio property.
     * 
     */
    public float getRatio() {
        return ratio;
    }

    /**
     * Sets the value of the ratio property.
     * 
     */
    public void setRatio(float value) {
        this.ratio = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CopyNumberAlterationType }
     *     
     */
    public CopyNumberAlterationType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CopyNumberAlterationType }
     *     
     */
    public void setType(CopyNumberAlterationType value) {
        this.type = value;
    }

    /**
     * Gets the value of the segmentLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSegmentLength() {
        return segmentLength;
    }

    /**
     * Sets the value of the segmentLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSegmentLength(Integer value) {
        this.segmentLength = value;
    }

}
