//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:12:17 PM CST 
//


package utsw.bicf.answer.model.ehr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://integration.foundationmedicine.com/reporting}ReferenceID"/>
 *         &lt;element ref="{http://integration.foundationmedicine.com/reporting}CSN"/>
 *         &lt;element ref="{http://integration.foundationmedicine.com/reporting}TRF"/>
 *         &lt;element ref="{http://integration.foundationmedicine.com/reporting}MRN"/>
 *         &lt;element ref="{http://integration.foundationmedicine.com/reporting}PhysicianId"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "referenceID",
    "csn",
    "trf",
    "mrn",
    "physicianId"
})
@XmlRootElement(name = "CustomerInformation")
public class CustomerInformation {

    @XmlElement(name = "ReferenceID", required = true)
    protected String referenceID;
    @XmlElement(name = "CSN", required = true)
    protected String csn;
    @XmlElement(name = "TRF", required = true)
    protected String trf;
    @XmlElement(name = "MRN", required = true)
    protected String mrn;
    @XmlElement(name = "PhysicianId", required = true)
    protected String physicianId;

    /**
     * Gets the value of the referenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceID() {
        return referenceID;
    }

    /**
     * Sets the value of the referenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceID(String value) {
        this.referenceID = value;
    }

    /**
     * Gets the value of the csn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSN() {
        return csn;
    }

    /**
     * Sets the value of the csn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSN(String value) {
        this.csn = value;
    }

    /**
     * Gets the value of the trf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRF() {
        return trf;
    }

    /**
     * Sets the value of the trf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRF(String value) {
        this.trf = value;
    }

    /**
     * Gets the value of the mrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMRN() {
        return mrn;
    }

    /**
     * Sets the value of the mrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMRN(String value) {
        this.mrn = value;
    }

    /**
     * Gets the value of the physicianId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicianId() {
        return physicianId;
    }

    /**
     * Sets the value of the physicianId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicianId(String value) {
        this.physicianId = value;
    }

}
