//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:46:26 PM CST 
//


package utsw.bicf.answer.model.ehr;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}Application"/>
 *         &lt;element ref="{}DemographicCorrectionDate" minOccurs="0"/>
 *         &lt;element ref="{}ReportId"/>
 *         &lt;element ref="{}SampleName"/>
 *         &lt;element ref="{}Version"/>
 *         &lt;element ref="{}Sample"/>
 *         &lt;element ref="{}PMI"/>
 *         &lt;element ref="{}PertinentNegatives"/>
 *         &lt;element ref="{}Summaries"/>
 *         &lt;element ref="{}VariantProperties" minOccurs="0"/>
 *         &lt;element ref="{}Genes"/>
 *         &lt;element ref="{}Trials"/>
 *         &lt;element ref="{}References"/>
 *         &lt;element ref="{}Signatures"/>
 *         &lt;element ref="{}AAC" minOccurs="0"/>
 *         &lt;element ref="{}Amendment" minOccurs="0"/>
 *         &lt;element ref="{}priorTests" minOccurs="0"/>
 *         &lt;element name="reportProperties" type="{}reportProperties" minOccurs="0"/>
 *         &lt;element name="comments" type="{}comments" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="StagingId" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="clinicalId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="PerformanceDataId" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "FinalReport")
public class FinalReport {

    @XmlElement(name = "Application", required = true)
    protected Application application;
    @XmlElement(name = "DemographicCorrectionDate")
    protected String demographicCorrectionDate;
    @XmlElement(name = "ReportId", required = true)
    protected String reportId;
    @XmlElement(name = "SampleName", required = true)
    protected String sampleName;
    @XmlElement(name = "Version", required = true)
    protected BigInteger version;
    @XmlElement(name = "Sample", required = true)
    protected Sample sample;
    @XmlElement(name = "PMI", required = true)
    protected PMI pmi;
    @XmlElement(name = "PertinentNegatives", required = true, nillable = true)
    protected PertinentNegatives pertinentNegatives;
    @XmlElement(name = "Summaries", required = true)
    protected Summaries summaries;
    @XmlElement(name = "VariantProperties")
    protected VariantProperties variantProperties;
    @XmlElement(name = "Genes", required = true)
    protected Genes genes;
    @XmlElement(name = "Trials", required = true)
    protected Trials trials;
    @XmlElement(name = "References", required = true)
    protected References references;
    @XmlElement(name = "Signatures", required = true)
    protected Signatures signatures;
    @XmlElement(name = "AAC")
    protected AAC aac;
    @XmlElement(name = "Amendment")
    protected Amendment amendment;
    protected PriorTests priorTests;
    protected ReportProperties reportProperties;
    protected Comments comments;
    @XmlAttribute(name = "StagingId")
    @XmlSchemaType(name = "anySimpleType")
    protected String stagingId;
    @XmlAttribute(name = "clinicalId", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String clinicalId;
    @XmlAttribute(name = "PerformanceDataId")
    @XmlSchemaType(name = "anySimpleType")
    protected String performanceDataId;

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link Application }
     *     
     */
    public Application getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link Application }
     *     
     */
    public void setApplication(Application value) {
        this.application = value;
    }

    /**
     * Gets the value of the demographicCorrectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDemographicCorrectionDate() {
        return demographicCorrectionDate;
    }

    /**
     * Sets the value of the demographicCorrectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDemographicCorrectionDate(String value) {
        this.demographicCorrectionDate = value;
    }

    /**
     * Gets the value of the reportId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * Sets the value of the reportId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportId(String value) {
        this.reportId = value;
    }

    /**
     * Gets the value of the sampleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleName() {
        return sampleName;
    }

    /**
     * Sets the value of the sampleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleName(String value) {
        this.sampleName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the sample property.
     * 
     * @return
     *     possible object is
     *     {@link Sample }
     *     
     */
    public Sample getSample() {
        return sample;
    }

    /**
     * Sets the value of the sample property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sample }
     *     
     */
    public void setSample(Sample value) {
        this.sample = value;
    }

    /**
     * Gets the value of the pmi property.
     * 
     * @return
     *     possible object is
     *     {@link PMI }
     *     
     */
    public PMI getPMI() {
        return pmi;
    }

    /**
     * Sets the value of the pmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link PMI }
     *     
     */
    public void setPMI(PMI value) {
        this.pmi = value;
    }

    /**
     * Gets the value of the pertinentNegatives property.
     * 
     * @return
     *     possible object is
     *     {@link PertinentNegatives }
     *     
     */
    public PertinentNegatives getPertinentNegatives() {
        return pertinentNegatives;
    }

    /**
     * Sets the value of the pertinentNegatives property.
     * 
     * @param value
     *     allowed object is
     *     {@link PertinentNegatives }
     *     
     */
    public void setPertinentNegatives(PertinentNegatives value) {
        this.pertinentNegatives = value;
    }

    /**
     * Gets the value of the summaries property.
     * 
     * @return
     *     possible object is
     *     {@link Summaries }
     *     
     */
    public Summaries getSummaries() {
        return summaries;
    }

    /**
     * Sets the value of the summaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summaries }
     *     
     */
    public void setSummaries(Summaries value) {
        this.summaries = value;
    }

    /**
     * Gets the value of the variantProperties property.
     * 
     * @return
     *     possible object is
     *     {@link VariantProperties }
     *     
     */
    public VariantProperties getVariantProperties() {
        return variantProperties;
    }

    /**
     * Sets the value of the variantProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantProperties }
     *     
     */
    public void setVariantProperties(VariantProperties value) {
        this.variantProperties = value;
    }

    /**
     * Gets the value of the genes property.
     * 
     * @return
     *     possible object is
     *     {@link Genes }
     *     
     */
    public Genes getGenes() {
        return genes;
    }

    /**
     * Sets the value of the genes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Genes }
     *     
     */
    public void setGenes(Genes value) {
        this.genes = value;
    }

    /**
     * Gets the value of the trials property.
     * 
     * @return
     *     possible object is
     *     {@link Trials }
     *     
     */
    public Trials getTrials() {
        return trials;
    }

    /**
     * Sets the value of the trials property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trials }
     *     
     */
    public void setTrials(Trials value) {
        this.trials = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link References }
     *     
     */
    public References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link References }
     *     
     */
    public void setReferences(References value) {
        this.references = value;
    }

    /**
     * Gets the value of the signatures property.
     * 
     * @return
     *     possible object is
     *     {@link Signatures }
     *     
     */
    public Signatures getSignatures() {
        return signatures;
    }

    /**
     * Sets the value of the signatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Signatures }
     *     
     */
    public void setSignatures(Signatures value) {
        this.signatures = value;
    }

    /**
     * Gets the value of the aac property.
     * 
     * @return
     *     possible object is
     *     {@link AAC }
     *     
     */
    public AAC getAAC() {
        return aac;
    }

    /**
     * Sets the value of the aac property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAC }
     *     
     */
    public void setAAC(AAC value) {
        this.aac = value;
    }

    /**
     * Gets the value of the amendment property.
     * 
     * @return
     *     possible object is
     *     {@link Amendment }
     *     
     */
    public Amendment getAmendment() {
        return amendment;
    }

    /**
     * Sets the value of the amendment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amendment }
     *     
     */
    public void setAmendment(Amendment value) {
        this.amendment = value;
    }

    /**
     * Gets the value of the priorTests property.
     * 
     * @return
     *     possible object is
     *     {@link PriorTests }
     *     
     */
    public PriorTests getPriorTests() {
        return priorTests;
    }

    /**
     * Sets the value of the priorTests property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorTests }
     *     
     */
    public void setPriorTests(PriorTests value) {
        this.priorTests = value;
    }

    /**
     * Gets the value of the reportProperties property.
     * 
     * @return
     *     possible object is
     *     {@link ReportProperties }
     *     
     */
    public ReportProperties getReportProperties() {
        return reportProperties;
    }

    /**
     * Sets the value of the reportProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportProperties }
     *     
     */
    public void setReportProperties(ReportProperties value) {
        this.reportProperties = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link Comments }
     *     
     */
    public Comments getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comments }
     *     
     */
    public void setComments(Comments value) {
        this.comments = value;
    }

    /**
     * Gets the value of the stagingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStagingId() {
        return stagingId;
    }

    /**
     * Sets the value of the stagingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStagingId(String value) {
        this.stagingId = value;
    }

    /**
     * Gets the value of the clinicalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalId() {
        return clinicalId;
    }

    /**
     * Sets the value of the clinicalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalId(String value) {
        this.clinicalId = value;
    }

    /**
     * Gets the value of the performanceDataId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerformanceDataId() {
        return performanceDataId;
    }

    /**
     * Sets the value of the performanceDataId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerformanceDataId(String value) {
        this.performanceDataId = value;
    }

}
