//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:46:26 PM CST 
//


package utsw.bicf.answer.model.ehr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element ref="{}ReportId" minOccurs="0"/>
 *         &lt;element ref="{}MRN" minOccurs="0"/>
 *         &lt;element ref="{}FullName" minOccurs="0"/>
 *         &lt;element ref="{}FirstName" minOccurs="0"/>
 *         &lt;element ref="{}LastName" minOccurs="0"/>
 *         &lt;element ref="{}SampleId" minOccurs="0"/>
 *         &lt;element ref="{}SubmittedDiagnosis" minOccurs="0"/>
 *         &lt;element ref="{}Gender" minOccurs="0"/>
 *         &lt;element ref="{}DOB" minOccurs="0"/>
 *         &lt;element ref="{}OrderingMD" minOccurs="0"/>
 *         &lt;element ref="{}OrderingMDId" minOccurs="0"/>
 *         &lt;element ref="{}Pathologist" minOccurs="0"/>
 *         &lt;element ref="{}CopiedPhysician1" minOccurs="0"/>
 *         &lt;element ref="{}MedFacilName" minOccurs="0"/>
 *         &lt;element ref="{}MedFacilID" minOccurs="0"/>
 *         &lt;element ref="{}SpecSite" minOccurs="0"/>
 *         &lt;element ref="{}CollDate" minOccurs="0"/>
 *         &lt;element ref="{}ReceivedDate" minOccurs="0"/>
 *         &lt;element ref="{}CountryOfOrigin" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "PMI")
public class PMI {

    @XmlElement(name = "ReportId")
    protected String reportId;
    @XmlElement(name = "MRN")
    protected String mrn;
    @XmlElement(name = "FullName")
    protected String fullName;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "SampleId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sampleId;
    @XmlElement(name = "SubmittedDiagnosis")
    protected String submittedDiagnosis;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "DOB")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String dob;
    @XmlElement(name = "OrderingMD")
    protected String orderingMD;
    @XmlElement(name = "OrderingMDId")
    protected String orderingMDId;
    @XmlElement(name = "Pathologist")
    protected String pathologist;
    @XmlElement(name = "CopiedPhysician1")
    protected String copiedPhysician1;
    @XmlElement(name = "MedFacilName")
    protected String medFacilName;
    @XmlElement(name = "MedFacilID")
    protected String medFacilID;
    @XmlElement(name = "SpecSite")
    protected String specSite;
    @XmlElement(name = "CollDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar collDate;
    @XmlElement(name = "ReceivedDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar receivedDate;
    @XmlElement(name = "CountryOfOrigin")
    protected String countryOfOrigin;

    /**
     * Gets the value of the reportId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * Sets the value of the reportId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportId(String value) {
        this.reportId = value;
    }

    /**
     * Gets the value of the mrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMRN() {
        return mrn;
    }

    /**
     * Sets the value of the mrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMRN(String value) {
        this.mrn = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the sampleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleId() {
        return sampleId;
    }

    /**
     * Sets the value of the sampleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleId(String value) {
        this.sampleId = value;
    }

    /**
     * Gets the value of the submittedDiagnosis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmittedDiagnosis() {
        return submittedDiagnosis;
    }

    /**
     * Sets the value of the submittedDiagnosis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmittedDiagnosis(String value) {
        this.submittedDiagnosis = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOB(String value) {
        this.dob = value;
    }

    /**
     * Gets the value of the orderingMD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingMD() {
        return orderingMD;
    }

    /**
     * Sets the value of the orderingMD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingMD(String value) {
        this.orderingMD = value;
    }

    /**
     * Gets the value of the orderingMDId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingMDId() {
        return orderingMDId;
    }

    /**
     * Sets the value of the orderingMDId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingMDId(String value) {
        this.orderingMDId = value;
    }

    /**
     * Gets the value of the pathologist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathologist() {
        return pathologist;
    }

    /**
     * Sets the value of the pathologist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathologist(String value) {
        this.pathologist = value;
    }

    /**
     * Gets the value of the copiedPhysician1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopiedPhysician1() {
        return copiedPhysician1;
    }

    /**
     * Sets the value of the copiedPhysician1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopiedPhysician1(String value) {
        this.copiedPhysician1 = value;
    }

    /**
     * Gets the value of the medFacilName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedFacilName() {
        return medFacilName;
    }

    /**
     * Sets the value of the medFacilName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedFacilName(String value) {
        this.medFacilName = value;
    }

    /**
     * Gets the value of the medFacilID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedFacilID() {
        return medFacilID;
    }

    /**
     * Sets the value of the medFacilID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedFacilID(String value) {
        this.medFacilID = value;
    }

    /**
     * Gets the value of the specSite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecSite() {
        return specSite;
    }

    /**
     * Sets the value of the specSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecSite(String value) {
        this.specSite = value;
    }

    /**
     * Gets the value of the collDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCollDate() {
        return collDate;
    }

    /**
     * Sets the value of the collDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCollDate(XMLGregorianCalendar value) {
        this.collDate = value;
    }

    /**
     * Gets the value of the receivedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReceivedDate() {
        return receivedDate;
    }

    /**
     * Sets the value of the receivedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReceivedDate(XMLGregorianCalendar value) {
        this.receivedDate = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin(String value) {
        this.countryOfOrigin = value;
    }

}
