//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:46:26 PM CST 
//


package utsw.bicf.answer.model.ehr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}priorAlterations"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="assayedInTests" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "priorAlterations"
})
@XmlRootElement(name = "priorGene")
public class PriorGene {

    @XmlElement(required = true)
    protected PriorAlterations priorAlterations;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "assayedInTests")
    protected String assayedInTests;

    /**
     * Gets the value of the priorAlterations property.
     * 
     * @return
     *     possible object is
     *     {@link PriorAlterations }
     *     
     */
    public PriorAlterations getPriorAlterations() {
        return priorAlterations;
    }

    /**
     * Sets the value of the priorAlterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorAlterations }
     *     
     */
    public void setPriorAlterations(PriorAlterations value) {
        this.priorAlterations = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the assayedInTests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssayedInTests() {
        return assayedInTests;
    }

    /**
     * Sets the value of the assayedInTests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssayedInTests(String value) {
        this.assayedInTests = value;
    }

}
