//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:12:17 PM CST 
//


package utsw.bicf.answer.model.ehr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
public class ResultsPayload {

    @XmlElement(name = "FinalReport", required = true)
    protected FinalReport finalReport;
    @XmlElement(name = "variant-report", required = true)
    protected VariantReport variantReport;
    @XmlElement(name = "PDFReport", required = true)
    protected String pdfReport;
    
	public FinalReport getFinalReport() {
		return finalReport;
	}
	public void setFinalReport(FinalReport finalReport) {
		this.finalReport = finalReport;
	}
	public VariantReport getVariantReport() {
		return variantReport;
	}
	public void setVariantReport(VariantReport variantReport) {
		this.variantReport = variantReport;
	}
	public String getPdfReport() {
		return pdfReport;
	}
	public void setPdfReport(String pdfReport) {
		this.pdfReport = pdfReport;
	}


}
