//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:46:26 PM CST 
//


package utsw.bicf.answer.model.ehr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}FM_Id"/>
 *         &lt;element ref="{}SampleId"/>
 *         &lt;element ref="{}BlockId" minOccurs="0"/>
 *         &lt;element ref="{}TRFNumber"/>
 *         &lt;element ref="{}TestType" minOccurs="0"/>
 *         &lt;element ref="{}SpecFormat"/>
 *         &lt;element ref="{}ReceivedDate"/>
 *         &lt;element name="processSites" type="{}processSites" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Sample")
public class Sample {

    @XmlElement(name = "FM_Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fmId;
    @XmlElement(name = "SampleId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sampleId;
    @XmlElement(name = "BlockId")
    protected String blockId;
    @XmlElement(name = "TRFNumber", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String trfNumber;
    @XmlElement(name = "TestType")
    protected String testType;
    @XmlElement(name = "SpecFormat", required = true)
    protected String specFormat;
    @XmlElement(name = "ReceivedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar receivedDate;
    protected ProcessSites processSites;

    /**
     * Gets the value of the fmId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMId() {
        return fmId;
    }

    /**
     * Sets the value of the fmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMId(String value) {
        this.fmId = value;
    }

    /**
     * Gets the value of the sampleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleId() {
        return sampleId;
    }

    /**
     * Sets the value of the sampleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleId(String value) {
        this.sampleId = value;
    }

    /**
     * Gets the value of the blockId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockId() {
        return blockId;
    }

    /**
     * Sets the value of the blockId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockId(String value) {
        this.blockId = value;
    }

    /**
     * Gets the value of the trfNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRFNumber() {
        return trfNumber;
    }

    /**
     * Sets the value of the trfNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRFNumber(String value) {
        this.trfNumber = value;
    }

    /**
     * Gets the value of the testType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestType() {
        return testType;
    }

    /**
     * Sets the value of the testType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestType(String value) {
        this.testType = value;
    }

    /**
     * Gets the value of the specFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecFormat() {
        return specFormat;
    }

    /**
     * Sets the value of the specFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecFormat(String value) {
        this.specFormat = value;
    }

    /**
     * Gets the value of the receivedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReceivedDate() {
        return receivedDate;
    }

    /**
     * Sets the value of the receivedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReceivedDate(XMLGregorianCalendar value) {
        this.receivedDate = value;
    }

    /**
     * Gets the value of the processSites property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessSites }
     *     
     */
    public ProcessSites getProcessSites() {
        return processSites;
    }

    /**
     * Sets the value of the processSites property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessSites }
     *     
     */
    public void setProcessSites(ProcessSites value) {
        this.processSites = value;
    }

}
