//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:46:26 PM CST 
//


package utsw.bicf.answer.model.ehr;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ClinicalTrialSummary" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="resistiveCount" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="alterationCount" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="clinicalTrialCount" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="sensitizingCount" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clinicalTrialSummary"
})
@XmlRootElement(name = "Summaries")
public class Summaries {

    @XmlElement(name = "ClinicalTrialSummary")
    protected String clinicalTrialSummary;
    @XmlAttribute(name = "resistiveCount", required = true)
    protected BigInteger resistiveCount;
    @XmlAttribute(name = "alterationCount", required = true)
    protected BigInteger alterationCount;
    @XmlAttribute(name = "clinicalTrialCount", required = true)
    protected BigInteger clinicalTrialCount;
    @XmlAttribute(name = "sensitizingCount", required = true)
    protected BigInteger sensitizingCount;

    /**
     * Gets the value of the clinicalTrialSummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalTrialSummary() {
        return clinicalTrialSummary;
    }

    /**
     * Sets the value of the clinicalTrialSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalTrialSummary(String value) {
        this.clinicalTrialSummary = value;
    }

    /**
     * Gets the value of the resistiveCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResistiveCount() {
        return resistiveCount;
    }

    /**
     * Sets the value of the resistiveCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResistiveCount(BigInteger value) {
        this.resistiveCount = value;
    }

    /**
     * Gets the value of the alterationCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAlterationCount() {
        return alterationCount;
    }

    /**
     * Sets the value of the alterationCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAlterationCount(BigInteger value) {
        this.alterationCount = value;
    }

    /**
     * Gets the value of the clinicalTrialCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClinicalTrialCount() {
        return clinicalTrialCount;
    }

    /**
     * Sets the value of the clinicalTrialCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClinicalTrialCount(BigInteger value) {
        this.clinicalTrialCount = value;
    }

    /**
     * Gets the value of the sensitizingCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSensitizingCount() {
        return sensitizingCount;
    }

    /**
     * Sets the value of the sensitizingCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSensitizingCount(BigInteger value) {
        this.sensitizingCount = value;
    }

}
