//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:46:26 PM CST 
//


package utsw.bicf.answer.model.ehr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}Name" minOccurs="0"/>
 *         &lt;element ref="{}GenericName" minOccurs="0"/>
 *         &lt;element ref="{}FDAApproved" minOccurs="0"/>
 *         &lt;element ref="{}Rationale" minOccurs="0"/>
 *         &lt;element ref="{}ApprovedUses" minOccurs="0"/>
 *         &lt;element ref="{}Effect" minOccurs="0"/>
 *         &lt;element ref="{}Include" minOccurs="0"/>
 *         &lt;element ref="{}IncludeInSummary" minOccurs="0"/>
 *         &lt;element ref="{}ReferenceLinks" minOccurs="0"/>
 *         &lt;element ref="{}ClinicalTrialLinks" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "genericName",
    "fdaApproved",
    "rationale",
    "approvedUses",
    "effect",
    "include",
    "includeInSummary",
    "referenceLinks",
    "clinicalTrialLinks"
})
@XmlRootElement(name = "Therapy")
public class Therapy {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "GenericName")
    protected String genericName;
    @XmlElement(name = "FDAApproved")
    protected Boolean fdaApproved;
    @XmlElement(name = "Rationale")
    protected String rationale;
    @XmlElement(name = "ApprovedUses")
    protected String approvedUses;
    @XmlElement(name = "Effect")
    protected String effect;
    @XmlElement(name = "Include")
    protected Boolean include;
    @XmlElement(name = "IncludeInSummary")
    protected Boolean includeInSummary;
    @XmlElement(name = "ReferenceLinks")
    protected ReferenceLinks referenceLinks;
    @XmlElement(name = "ClinicalTrialLinks")
    protected ClinicalTrialLinks clinicalTrialLinks;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the genericName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenericName() {
        return genericName;
    }

    /**
     * Sets the value of the genericName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenericName(String value) {
        this.genericName = value;
    }

    /**
     * Gets the value of the fdaApproved property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFDAApproved() {
        return fdaApproved;
    }

    /**
     * Sets the value of the fdaApproved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFDAApproved(Boolean value) {
        this.fdaApproved = value;
    }

    /**
     * Gets the value of the rationale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRationale() {
        return rationale;
    }

    /**
     * Sets the value of the rationale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRationale(String value) {
        this.rationale = value;
    }

    /**
     * Gets the value of the approvedUses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedUses() {
        return approvedUses;
    }

    /**
     * Sets the value of the approvedUses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedUses(String value) {
        this.approvedUses = value;
    }

    /**
     * Gets the value of the effect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffect() {
        return effect;
    }

    /**
     * Sets the value of the effect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffect(String value) {
        this.effect = value;
    }

    /**
     * Gets the value of the include property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInclude() {
        return include;
    }

    /**
     * Sets the value of the include property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInclude(Boolean value) {
        this.include = value;
    }

    /**
     * Gets the value of the includeInSummary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeInSummary() {
        return includeInSummary;
    }

    /**
     * Sets the value of the includeInSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeInSummary(Boolean value) {
        this.includeInSummary = value;
    }

    /**
     * Gets the value of the referenceLinks property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceLinks }
     *     
     */
    public ReferenceLinks getReferenceLinks() {
        return referenceLinks;
    }

    /**
     * Sets the value of the referenceLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceLinks }
     *     
     */
    public void setReferenceLinks(ReferenceLinks value) {
        this.referenceLinks = value;
    }

    /**
     * Gets the value of the clinicalTrialLinks property.
     * 
     * @return
     *     possible object is
     *     {@link ClinicalTrialLinks }
     *     
     */
    public ClinicalTrialLinks getClinicalTrialLinks() {
        return clinicalTrialLinks;
    }

    /**
     * Sets the value of the clinicalTrialLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClinicalTrialLinks }
     *     
     */
    public void setClinicalTrialLinks(ClinicalTrialLinks value) {
        this.clinicalTrialLinks = value;
    }

}
