//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:46:26 PM CST 
//


package utsw.bicf.answer.model.ehr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Gene" minOccurs="0"/>
 *         &lt;element ref="{}Alteration"/>
 *         &lt;element ref="{}Title"/>
 *         &lt;element ref="{}Summary" minOccurs="0"/>
 *         &lt;element ref="{}StudyPhase"/>
 *         &lt;element ref="{}Condition" minOccurs="0"/>
 *         &lt;element ref="{}Target" minOccurs="0"/>
 *         &lt;element ref="{}Eligibility" minOccurs="0"/>
 *         &lt;element ref="{}Locations" minOccurs="0"/>
 *         &lt;element ref="{}NCTID"/>
 *         &lt;element ref="{}Note" minOccurs="0"/>
 *         &lt;element ref="{}Include"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gene",
    "alteration",
    "title",
    "summary",
    "studyPhase",
    "condition",
    "target",
    "eligibility",
    "locations",
    "nctid",
    "note",
    "include"
})
@XmlRootElement(name = "Trial")
public class Trial {

    @XmlElement(name = "Gene")
    protected Gene gene;
    @XmlElement(name = "Alteration", required = true)
    protected Alteration alteration;
    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "Summary")
    protected Summary summary;
    @XmlElement(name = "StudyPhase", required = true)
    protected String studyPhase;
    @XmlElement(name = "Condition")
    protected String condition;
    @XmlElement(name = "Target")
    protected String target;
    @XmlElement(name = "Eligibility")
    protected String eligibility;
    @XmlElement(name = "Locations")
    protected String locations;
    @XmlElement(name = "NCTID", required = true)
    protected String nctid;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "Include")
    protected boolean include;

    /**
     * Gets the value of the gene property.
     * 
     * @return
     *     possible object is
     *     {@link Gene }
     *     
     */
    public Gene getGene() {
        return gene;
    }

    /**
     * Sets the value of the gene property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gene }
     *     
     */
    public void setGene(Gene value) {
        this.gene = value;
    }

    /**
     * Gets the value of the alteration property.
     * 
     * @return
     *     possible object is
     *     {@link Alteration }
     *     
     */
    public Alteration getAlteration() {
        return alteration;
    }

    /**
     * Sets the value of the alteration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alteration }
     *     
     */
    public void setAlteration(Alteration value) {
        this.alteration = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link Summary }
     *     
     */
    public Summary getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary }
     *     
     */
    public void setSummary(Summary value) {
        this.summary = value;
    }

    /**
     * Gets the value of the studyPhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudyPhase() {
        return studyPhase;
    }

    /**
     * Sets the value of the studyPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudyPhase(String value) {
        this.studyPhase = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the eligibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibility() {
        return eligibility;
    }

    /**
     * Sets the value of the eligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibility(String value) {
        this.eligibility = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocations(String value) {
        this.locations = value;
    }

    /**
     * Gets the value of the nctid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCTID() {
        return nctid;
    }

    /**
     * Sets the value of the nctid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCTID(String value) {
        this.nctid = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the include property.
     * 
     */
    public boolean isInclude() {
        return include;
    }

    /**
     * Sets the value of the include property.
     * 
     */
    public void setInclude(boolean value) {
        this.include = value;
    }

}
