//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:28:17 PM CST 
//


package utsw.bicf.answer.model.ehr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VariantReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VariantReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="samples">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="sample" type="{http://foundationmedicine.com/compbio/variant-report-external}Sample" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="quality-control" type="{http://foundationmedicine.com/compbio/variant-report-external}QualityControl"/>
 *         &lt;element name="short-variants">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="short-variant" type="{http://foundationmedicine.com/compbio/variant-report-external}ShortVariant" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="copy-number-alterations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="copy-number-alteration" type="{http://foundationmedicine.com/compbio/variant-report-external}CopyNumberAlteration" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rearrangements">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rearrangement" type="{http://foundationmedicine.com/compbio/variant-report-external}Rearrangement" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="biomarkers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="microsatellite-instability" type="{http://foundationmedicine.com/compbio/variant-report-external}MicrosatelliteInstability" minOccurs="0"/>
 *                   &lt;element name="tumor-mutation-burden" type="{http://foundationmedicine.com/compbio/variant-report-external}TumorMutationBurden" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="non-human-content">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="non-human" type="{http://foundationmedicine.com/compbio/variant-report-external}NonHuman" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="standard-nucleic-acid-types" type="{http://foundationmedicine.com/compbio/variant-report-external}NucleicAcidTypeList" />
 *       &lt;attribute name="disease" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gender" type="{http://foundationmedicine.com/compbio/variant-report-external}Gender" />
 *       &lt;attribute name="test-request" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="flowcell-analysis" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tissue-of-origin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pathology-diagnosis" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="study" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="disease-ontology" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pipeline-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="test-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="percent-tumor-nuclei" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="purity-assessment" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="specimen" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VariantReport", propOrder = {
    "samples",
    "qualityControl",
    "shortVariants",
    "copyNumberAlterations",
    "rearrangements",
    "biomarkers",
    "nonHumanContent"
})
public class VariantReport {

    @XmlElement(required = true)
    protected VariantReport.Samples samples;
    @XmlElement(name = "quality-control", required = true)
    protected QualityControl qualityControl;
    @XmlElement(name = "short-variants", required = true)
    protected VariantReport.ShortVariants shortVariants;
    @XmlElement(name = "copy-number-alterations", required = true)
    protected VariantReport.CopyNumberAlterations copyNumberAlterations;
    @XmlElement(required = true)
    protected VariantReport.Rearrangements rearrangements;
    protected VariantReport.Biomarkers biomarkers;
    @XmlElement(name = "non-human-content", required = true)
    protected VariantReport.NonHumanContent nonHumanContent;
    @XmlAttribute(name = "standard-nucleic-acid-types")
    protected List<NucleicAcidTypeEnum> standardNucleicAcidTypes;
    @XmlAttribute(name = "disease")
    protected String disease;
    @XmlAttribute(name = "gender")
    protected Gender gender;
    @XmlAttribute(name = "test-request")
    protected String testRequest;
    @XmlAttribute(name = "flowcell-analysis")
    protected Integer flowcellAnalysis;
    @XmlAttribute(name = "tissue-of-origin")
    protected String tissueOfOrigin;
    @XmlAttribute(name = "pathology-diagnosis")
    protected String pathologyDiagnosis;
    @XmlAttribute(name = "study")
    protected String study;
    @XmlAttribute(name = "disease-ontology")
    protected String diseaseOntology;
    @XmlAttribute(name = "pipeline-version")
    protected String pipelineVersion;
    @XmlAttribute(name = "test-type")
    protected String testType;
    @XmlAttribute(name = "percent-tumor-nuclei")
    protected String percentTumorNuclei;
    @XmlAttribute(name = "purity-assessment")
    protected Float purityAssessment;
    @XmlAttribute(name = "specimen", required = true)
    protected String specimen;

    /**
     * Gets the value of the samples property.
     * 
     * @return
     *     possible object is
     *     {@link VariantReport.Samples }
     *     
     */
    public VariantReport.Samples getSamples() {
        return samples;
    }

    /**
     * Sets the value of the samples property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantReport.Samples }
     *     
     */
    public void setSamples(VariantReport.Samples value) {
        this.samples = value;
    }

    /**
     * Gets the value of the qualityControl property.
     * 
     * @return
     *     possible object is
     *     {@link QualityControl }
     *     
     */
    public QualityControl getQualityControl() {
        return qualityControl;
    }

    /**
     * Sets the value of the qualityControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityControl }
     *     
     */
    public void setQualityControl(QualityControl value) {
        this.qualityControl = value;
    }

    /**
     * Gets the value of the shortVariants property.
     * 
     * @return
     *     possible object is
     *     {@link VariantReport.ShortVariants }
     *     
     */
    public VariantReport.ShortVariants getShortVariants() {
        return shortVariants;
    }

    /**
     * Sets the value of the shortVariants property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantReport.ShortVariants }
     *     
     */
    public void setShortVariants(VariantReport.ShortVariants value) {
        this.shortVariants = value;
    }

    /**
     * Gets the value of the copyNumberAlterations property.
     * 
     * @return
     *     possible object is
     *     {@link VariantReport.CopyNumberAlterations }
     *     
     */
    public VariantReport.CopyNumberAlterations getCopyNumberAlterations() {
        return copyNumberAlterations;
    }

    /**
     * Sets the value of the copyNumberAlterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantReport.CopyNumberAlterations }
     *     
     */
    public void setCopyNumberAlterations(VariantReport.CopyNumberAlterations value) {
        this.copyNumberAlterations = value;
    }

    /**
     * Gets the value of the rearrangements property.
     * 
     * @return
     *     possible object is
     *     {@link VariantReport.Rearrangements }
     *     
     */
    public VariantReport.Rearrangements getRearrangements() {
        return rearrangements;
    }

    /**
     * Sets the value of the rearrangements property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantReport.Rearrangements }
     *     
     */
    public void setRearrangements(VariantReport.Rearrangements value) {
        this.rearrangements = value;
    }

    /**
     * Gets the value of the biomarkers property.
     * 
     * @return
     *     possible object is
     *     {@link VariantReport.Biomarkers }
     *     
     */
    public VariantReport.Biomarkers getBiomarkers() {
        return biomarkers;
    }

    /**
     * Sets the value of the biomarkers property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantReport.Biomarkers }
     *     
     */
    public void setBiomarkers(VariantReport.Biomarkers value) {
        this.biomarkers = value;
    }

    /**
     * Gets the value of the nonHumanContent property.
     * 
     * @return
     *     possible object is
     *     {@link VariantReport.NonHumanContent }
     *     
     */
    public VariantReport.NonHumanContent getNonHumanContent() {
        return nonHumanContent;
    }

    /**
     * Sets the value of the nonHumanContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantReport.NonHumanContent }
     *     
     */
    public void setNonHumanContent(VariantReport.NonHumanContent value) {
        this.nonHumanContent = value;
    }

    /**
     * Gets the value of the standardNucleicAcidTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardNucleicAcidTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardNucleicAcidTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NucleicAcidTypeEnum }
     * 
     * 
     */
    public List<NucleicAcidTypeEnum> getStandardNucleicAcidTypes() {
        if (standardNucleicAcidTypes == null) {
            standardNucleicAcidTypes = new ArrayList<NucleicAcidTypeEnum>();
        }
        return this.standardNucleicAcidTypes;
    }

    /**
     * Gets the value of the disease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisease() {
        return disease;
    }

    /**
     * Sets the value of the disease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisease(String value) {
        this.disease = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Gender }
     *     
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gender }
     *     
     */
    public void setGender(Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the testRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestRequest() {
        return testRequest;
    }

    /**
     * Sets the value of the testRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestRequest(String value) {
        this.testRequest = value;
    }

    /**
     * Gets the value of the flowcellAnalysis property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFlowcellAnalysis() {
        return flowcellAnalysis;
    }

    /**
     * Sets the value of the flowcellAnalysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFlowcellAnalysis(Integer value) {
        this.flowcellAnalysis = value;
    }

    /**
     * Gets the value of the tissueOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTissueOfOrigin() {
        return tissueOfOrigin;
    }

    /**
     * Sets the value of the tissueOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTissueOfOrigin(String value) {
        this.tissueOfOrigin = value;
    }

    /**
     * Gets the value of the pathologyDiagnosis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathologyDiagnosis() {
        return pathologyDiagnosis;
    }

    /**
     * Sets the value of the pathologyDiagnosis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathologyDiagnosis(String value) {
        this.pathologyDiagnosis = value;
    }

    /**
     * Gets the value of the study property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudy() {
        return study;
    }

    /**
     * Sets the value of the study property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudy(String value) {
        this.study = value;
    }

    /**
     * Gets the value of the diseaseOntology property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiseaseOntology() {
        return diseaseOntology;
    }

    /**
     * Sets the value of the diseaseOntology property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiseaseOntology(String value) {
        this.diseaseOntology = value;
    }

    /**
     * Gets the value of the pipelineVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPipelineVersion() {
        return pipelineVersion;
    }

    /**
     * Sets the value of the pipelineVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPipelineVersion(String value) {
        this.pipelineVersion = value;
    }

    /**
     * Gets the value of the testType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestType() {
        return testType;
    }

    /**
     * Sets the value of the testType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestType(String value) {
        this.testType = value;
    }

    /**
     * Gets the value of the percentTumorNuclei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentTumorNuclei() {
        return percentTumorNuclei;
    }

    /**
     * Sets the value of the percentTumorNuclei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentTumorNuclei(String value) {
        this.percentTumorNuclei = value;
    }

    /**
     * Gets the value of the purityAssessment property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPurityAssessment() {
        return purityAssessment;
    }

    /**
     * Sets the value of the purityAssessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPurityAssessment(Float value) {
        this.purityAssessment = value;
    }

    /**
     * Gets the value of the specimen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecimen() {
        return specimen;
    }

    /**
     * Sets the value of the specimen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecimen(String value) {
        this.specimen = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="microsatellite-instability" type="{http://foundationmedicine.com/compbio/variant-report-external}MicrosatelliteInstability" minOccurs="0"/>
     *         &lt;element name="tumor-mutation-burden" type="{http://foundationmedicine.com/compbio/variant-report-external}TumorMutationBurden" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "microsatelliteInstability",
        "tumorMutationBurden"
    })
    public static class Biomarkers {

        @XmlElement(name = "microsatellite-instability")
        protected MicrosatelliteInstability microsatelliteInstability;
        @XmlElement(name = "tumor-mutation-burden")
        protected TumorMutationBurden tumorMutationBurden;

        /**
         * Gets the value of the microsatelliteInstability property.
         * 
         * @return
         *     possible object is
         *     {@link MicrosatelliteInstability }
         *     
         */
        public MicrosatelliteInstability getMicrosatelliteInstability() {
            return microsatelliteInstability;
        }

        /**
         * Sets the value of the microsatelliteInstability property.
         * 
         * @param value
         *     allowed object is
         *     {@link MicrosatelliteInstability }
         *     
         */
        public void setMicrosatelliteInstability(MicrosatelliteInstability value) {
            this.microsatelliteInstability = value;
        }

        /**
         * Gets the value of the tumorMutationBurden property.
         * 
         * @return
         *     possible object is
         *     {@link TumorMutationBurden }
         *     
         */
        public TumorMutationBurden getTumorMutationBurden() {
            return tumorMutationBurden;
        }

        /**
         * Sets the value of the tumorMutationBurden property.
         * 
         * @param value
         *     allowed object is
         *     {@link TumorMutationBurden }
         *     
         */
        public void setTumorMutationBurden(TumorMutationBurden value) {
            this.tumorMutationBurden = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="copy-number-alteration" type="{http://foundationmedicine.com/compbio/variant-report-external}CopyNumberAlteration" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "copyNumberAlteration"
    })
    public static class CopyNumberAlterations {

        @XmlElement(name = "copy-number-alteration")
        protected List<CopyNumberAlteration> copyNumberAlteration;

        /**
         * Gets the value of the copyNumberAlteration property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the copyNumberAlteration property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCopyNumberAlteration().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CopyNumberAlteration }
         * 
         * 
         */
        public List<CopyNumberAlteration> getCopyNumberAlteration() {
            if (copyNumberAlteration == null) {
                copyNumberAlteration = new ArrayList<CopyNumberAlteration>();
            }
            return this.copyNumberAlteration;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="non-human" type="{http://foundationmedicine.com/compbio/variant-report-external}NonHuman" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nonHuman"
    })
    public static class NonHumanContent {

        @XmlElement(name = "non-human")
        protected List<NonHuman> nonHuman;

        /**
         * Gets the value of the nonHuman property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nonHuman property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNonHuman().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NonHuman }
         * 
         * 
         */
        public List<NonHuman> getNonHuman() {
            if (nonHuman == null) {
                nonHuman = new ArrayList<NonHuman>();
            }
            return this.nonHuman;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rearrangement" type="{http://foundationmedicine.com/compbio/variant-report-external}Rearrangement" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rearrangement"
    })
    public static class Rearrangements {

        protected List<Rearrangement> rearrangement;

        /**
         * Gets the value of the rearrangement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rearrangement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRearrangement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Rearrangement }
         * 
         * 
         */
        public List<Rearrangement> getRearrangement() {
            if (rearrangement == null) {
                rearrangement = new ArrayList<Rearrangement>();
            }
            return this.rearrangement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="sample" type="{http://foundationmedicine.com/compbio/variant-report-external}Sample" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sample"
    })
    public static class Samples {

        @XmlElement(required = true)
        protected List<Sample> sample;

        /**
         * Gets the value of the sample property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sample property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSample().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Sample }
         * 
         * 
         */
        public List<Sample> getSample() {
            if (sample == null) {
                sample = new ArrayList<Sample>();
            }
            return this.sample;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="short-variant" type="{http://foundationmedicine.com/compbio/variant-report-external}ShortVariant" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shortVariant"
    })
    public static class ShortVariants {

        @XmlElement(name = "short-variant")
        protected List<ShortVariant> shortVariant;

        /**
         * Gets the value of the shortVariant property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the shortVariant property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getShortVariant().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ShortVariant }
         * 
         * 
         */
        public List<ShortVariant> getShortVariant() {
            if (shortVariant == null) {
                shortVariant = new ArrayList<ShortVariant>();
            }
            return this.shortVariant;
        }

    }

}
