//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 02:28:17 PM CST 
//


package utsw.bicf.answer.model.ehr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Variant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Variant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="status" use="required" type="{http://foundationmedicine.com/compbio/variant-report-external}VariantStatus" />
 *       &lt;attribute name="equivocal" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Variant")
@XmlSeeAlso({
    CopyNumberAlteration.class,
    ShortVariant.class,
    Rearrangement.class
})
public class Variant {

    @XmlAttribute(name = "status", required = true)
    protected VariantStatus status;
    @XmlAttribute(name = "equivocal")
    protected Boolean equivocal;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link VariantStatus }
     *     
     */
    public VariantStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantStatus }
     *     
     */
    public void setStatus(VariantStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the equivocal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEquivocal() {
        if (equivocal == null) {
            return false;
        } else {
            return equivocal;
        }
    }

    /**
     * Sets the value of the equivocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEquivocal(Boolean value) {
        this.equivocal = value;
    }

}
